### ISSUE TITLE
[BUG] Icon red box

### ISSUE THREAD

**Issue by LangLangBart** [Friss/TwitchNotifier#10]
Thank you for taking the time to program this extension and make it available to the public. 

The old icon was the better version in my opinion, the new one has a little red box ("Live") that I always mistakenly think is indicator for a notification.
![old_new](https://user-images.githubusercontent.com/92653266/156929787-dda25e43-6c9b-4186-a3d3-be7aea92d47a.png)

**Comment by Friss** [comment]
Unfortunately the Chrome store policy prohibits me from using the Twitch logo for the extension. 

That said I can change the icon, is it just the red color that is the problem?

**Comment by LangLangBart** [comment]
> That said I can change the icon, is it just the red color that is the problem?

The little red box is the only issue I have encountered, otherwise this extension is great. It does exactly what I was looking for.

**Comment by Friss** [comment]
How about changing the color to be green? 

![logo](https://user-images.githubusercontent.com/4588318/157120445-264db3af-cfc3-4bd4-8bb9-a8935c2620b1.png)

It would match the green of the real notification badge. 
<img width="37" alt="Screen Shot 2022-03-07 at 4 28 34 PM" src="https://user-images.githubusercontent.com/4588318/157121165-f552be60-d91c-4211-b9e8-c991e3e912f7.png">

Otherwise could also center the logo and drop the "live" badge. 
![logo-centered](https://user-images.githubusercontent.com/4588318/157123260-564ecafd-9f42-4450-808f-ef1553c34d35.png)

**Comment by LangLangBart** [comment]
I would vote for the second version without the colored box.

**Comment by farzher** [comment]
i was about to post this same issue. that red is so distracting! neat extension, twitch notifications never work for me. ty!

![](https://i.imgur.com/YB4p6Cl.png)
